/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jrksurqtennacxmotgzq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impya3N1cnF0ZW5uYWN4bW90Z3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2MDA3NjksImV4cCI6MjA4NzE3Njc2OX0.Z-qRiDecrRlWTBFOuI9r7u6i4kt3GEv9SYZixUC-tGI"